name: Data Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - staging
    paths:
      - .github/workflows/flat.yml
      - ./postprocess.js

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.33.x
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Fetch data
        uses: githubocto/flat@v3.3.1
        with:
          http_url: https://neteon.webflow.io/homepage-templete-version-20240522
          downloaded_filename: webflow.html
          postprocess: ./postprocess.js
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Update data"
          git push origin staging
  create-pull-request:
    needs: fetch-data
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          ref: staging
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: staging
          title: "Data update from Staging"
          body: "This is an automated pull request to update data from the staging branch to the main branch."
